- src/app/graphs/label-trend.ts
- src/app/item-detail/label-trend/label-trend.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/14
> trend limit change

- src/app/item-detail/performance-analysis/performance-analysis.component.ts
fix for https://github.com/ludeknovy/jtl-reporter/issues/26
> zero value fix

- src/app/item-detail/item-detail.component.html
- src/app/item-detail/item-detail.component.scss
https://github.com/ludeknovy/jtl-reporter/issues/44
> sut statistics

- src/app/graphs/scenario-trends.ts
- src/app/scenario/scenario-trends/scenario-trends.component.html
- src/app/scenario/scenario-trends/scenario-trends.component.spec.ts
- src/app/scenario/scenario-trends/scenario-trends.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/32
> scenario trend column clickable

- src/app/item-detail/label-chart/label-chart.component.css
- src/app/item-detail/label-chart/label-chart.component.html
- src/app/item-detail/label-chart/label-chart.component.ts
- src/index.html
https://github.com/ludeknovy/jtl-reporter/issues/40
> label chart collapsable

- src/app/scenario/scenario-trends/scenario-trends.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/98
> scenario network chart

- src/app/app.module.ts
- src/app/item-detail/item-detail.component.html
- src/app/item-detail/item-detail.component.ts
- src/app/item-detail/request-stats/label-health/label-health.component.ts
- src/app/item-detail/zero-error-tolerance-warning/zero-error-tolerance-warning.component.css
- src/app/item-detail/zero-error-tolerance-warning/zero-error-tolerance-warning.component.html
- src/app/item-detail/zero-error-tolerance-warning/zero-error-tolerance-warning.component.spec.ts
- src/app/item-detail/zero-error-tolerance-warning/zero-error-tolerance-warning.component.ts
- src/app/items.service.model.ts
- src/app/scenario.service.model.ts
- src/app/scenario/scenario-settings/scenario-settings.component.html
- src/app/scenario/scenario-settings/scenario-settings.component.ts
- src/app/scenario/scenario.component.html
- src/app/scenario/scenario.component.scss
- src/app/scenario/scenario.component.ts
- src/app/utils/showZeroErrorTolerance.ts
https://github.com/ludeknovy/jtl-reporter/issues/103
> scenario zero error toleration

- src/app/_pipes/url-decode.module.ts
- src/app/_pipes/url-decode.pipe.spec.ts
- src/app/_pipes/url-decode.pipe.ts
- src/app/_pipes/url-encode.module.ts
- src/app/_pipes/url-encode.pipe.spec.ts
- src/app/_pipes/url-encode.pipe.ts
- src/app/administration/projects/administration.component.html
- src/app/administration/projects/project-administration.module.ts
- src/app/app.module.ts
- src/app/project/project.component.html
- src/app/project/project.module.ts
- src/app/scenario/scenario-settings/scenario-settings.component.ts
- src/app/shared/breadcrumb/breadcrumb.component.html
- src/app/shared/shared-project/project-settings/project-settings.component.ts
- src/app/shared/shared.module.ts
- src/app/top-panel/top-panel.component.html
- src/app/top-panel/top-panel.module.ts
https://github.com/ludeknovy/jtl-reporter/issues/111
> scenario and project name encoding fix

- src/app/item-detail/request-stats/label-health/label-health.component.html
https://github.com/ludeknovy/jtl-reporter/issues/115
> responseMessageFailures status code

- src/app/shared/shared-item/edit-item/edit-item.component.css
- src/app/shared/shared-item/edit-item/edit-item.component.html
- src/app/shared/shared-item/edit-item/edit-item.module.ts
https://github.com/ludeknovy/jtl-reporter/issues/121
> base run tooltip

- src/app/graphs/label-trend.ts
https://github.com/ludeknovy/jtl-reporter/issues/124
> label trend chart: stacking disabled

- src/app/item-detail/request-stats/label-health/label-health.component.html
https://github.com/ludeknovy/jtl-reporter/issues/114
> label health failure message

- src/app/item-detail/calculations.ts
- src/app/item-detail/request-stats/request-stats-compare.component.html
- src/app/item-detail/request-stats/request-stats-compare.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/137
> comparison max number of decimals

- src/app/scenario/scenario-settings/scenario-settings.component.css
- src/app/scenario/scenario-settings/scenario-settings.component.html
- src/app/scenario/scenario-settings/scenario-settings.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/136
> generate share token scenario settings

- src/app/item-detail/item-detail.component.html
- src/app/shared/shared-project/project-settings/project-settings.component.html
- src/app/shared/shared-project/project-settings/project-settings.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/141
> top stats extended

- src/app/item-detail/request-stats/request-stats-compare.component.html
- src/app/item-detail/request-stats/request-stats-compare.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/143
> samples comparison

- package-lock.json
- package.json
- src/app/item-detail/request-stats/request-stats-compare.component.css
- src/app/item-detail/request-stats/request-stats-compare.component.html
- src/app/item-detail/request-stats/request-stats-compare.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/146
> Download request stats as png

- package-lock.json
- package.json
- src/app/_services/excel.service.ts
- src/app/item-detail/item-detail.module.ts
- src/app/item-detail/request-stats/request-stats-compare.component.html
- src/app/item-detail/request-stats/request-stats-compare.component.spec.ts
- src/app/item-detail/request-stats/request-stats-compare.component.ts
- src/app/item-detail/stats-compare/stats-compare.component.css
- src/app/item-detail/stats-compare/stats-compare.component.html
https://github.com/ludeknovy/jtl-reporter/issues/146
> Download request stats as excel

- src/app/graphs/item-detail.ts
- src/app/graphs/label-trend.ts
- src/app/graphs/monitoring.ts
- src/app/graphs/scenario-trends.ts
https://github.com/ludeknovy/jtl-reporter/issues/150
> fix: chart max 2 decimals

- src/app/graphs/item-detail.ts
- src/app/graphs/scenario-trends.ts
- src/app/item-detail/analyze-charts/analyze-charts.component.spec.ts
- src/app/item-detail/analyze-charts/analyze-charts.component.ts
- src/app/item-detail/item-detail.component.ts
- src/app/scenario/scenario-trends/scenario-trends.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/152
> chart tooltip units

- src/app/graphs/label-trend.ts
- src/app/item-detail/label-trend/label-trend.component.html
- src/app/item-detail/label-trend/label-trend.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/157
> label trend exporting button

- src/app/graphs/label-trend.ts
- src/app/item-detail/label-trend/label-trend.component.css
- src/app/item-detail/label-trend/label-trend.component.html
- src/app/item-detail/label-trend/label-trend.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/156
> display bar values for label trend chart

- src/app/item-detail/request-stats/request-stats-compare.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/158
> header names fix

- src/app/graphs/label-trend.ts
- src/app/item-detail/analyze-charts/analyze-charts.component.ts
- src/app/item-detail/label-trend/label-trend.component.ts
- src/app/items.service.model.ts
- src/app/scenario/scenario-settings/scenario-settings.component.html
- src/app/scenario/scenario-settings/scenario-settings.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/155
> label trend chart scenario settings

- src/app/graphs/item-detail.ts
- src/app/item-detail/analyze-charts/analyze-charts.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/151
> custom chart yaxis visibility fix

- src/app/graphs/item-detail.ts
- src/app/graphs/label-trend.ts
- src/app/graphs/scenario-trends.ts
- src/app/item-detail/item-detail.component.html
- src/app/item-detail/item-detail.component.ts
- src/app/item-detail/label-chart/label-chart.component.ts
- src/app/item-detail/request-stats/request-stats-compare.component.html
- src/app/item-detail/request-stats/request-stats-compare.component.ts
- src/app/scenario/scenario-trends/scenario-trends.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/149
> units unification - reqs/s instead of hit(s)/s, request stats headers unit fixes

- src/app/item-detail/request-stats/request-stats-compare.component.html
- src/app/item-detail/request-stats/request-stats-compare.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/163
> request stats comparison percentage

- src/app/_services/item-chart.service.spec.ts
- src/app/_services/item-chart.service.ts
- src/app/item-detail/analyze-charts/analyze-charts.component.ts
- src/app/item-detail/chart-interval/chart-interval.component.html
- src/app/item-detail/chart-interval/chart-interval.component.spec.ts
- src/app/item-detail/chart-interval/chart-interval.component.ts
- src/app/item-detail/item-detail.component.html
- src/app/item-detail/item-detail.component.ts
- src/app/item-detail/item-detail.module.ts
- src/app/item-detail/label-chart/label-chart.component.spec.ts
- src/app/item-detail/label-chart/label-chart.component.ts
- src/app/items.service.model.ts
- src/app/scenario/scenario-settings/scenario-settings.component.css
- src/app/scenario/scenario-settings/scenario-settings.component.html
- src/app/scenario/scenario-settings/scenario-settings.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/142
> Extra item interval select

- src/app/item-detail/label-trend/label-trend.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/171
> label trend chart print fix

- src/app/graphs/label-trend.ts
https://github.com/ludeknovy/jtl-reporter/issues/172
> display zero value columns

- src/app/scenario/external-notification/add-new-external-notification/add-new-external-notification.component.html
- src/app/scenario/external-notification/add-new-external-notification/add-new-external-notification.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/179
> gchat notification

- src/app/scenario/external-notification/add-new-external-notification/add-new-external-notification.component.html
- src/app/scenario/external-notification/add-new-external-notification/add-new-external-notification.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/181
> Slack notification

- src/app/scenario/scenario-settings/scenario-settings.component.css
- src/app/scenario/scenario-settings/scenario-settings.component.html
- src/app/shared/shared-project/project-settings/project-settings.component.html
- src/app/shared/shared-project/project-settings/project-settings.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/190
> Scenario upsert form control

- src/app/item-detail/item-detail.component.ts
- src/app/item-detail/request-stats/request-stats-compare.component.html
- src/app/item-detail/request-stats/request-stats-compare.component.spec.ts
- src/app/item-detail/request-stats/request-stats-compare.component.ts
- src/app/items.service.model.ts
- src/app/scenario.service.model.ts
- src/app/scenario/scenario-settings/scenario-settings.component.html
- src/app/scenario/scenario-settings/scenario-settings.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/194
> scenario configure request stats table

- src/app/item-detail/request-stats/request-stats-compare.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/194
> xlxs exported data parametrized based on user settings

- src/app/administration/projects/add-project/add-project-modal.component.html
https://github.com/ludeknovy/jtl-reporter/issues/52
> New project plus icon

- .github/workflows/build.yml
- .github/workflows/static-analysis.yml
- Dockerfile
https://github.com/ludeknovy/jtl-reporter/issues/199
> node upgrade - v18

- src/app/graphs/item-detail.ts
- src/app/graphs/scenario-trends.ts
- src/app/item-detail/label-chart/label-chart.component.ts
- src/app/items.service.model.ts
- src/app/notification/notification-messages.ts
- src/app/scenario-api.service.ts
- src/app/scenario.service.ts
- src/app/scenario/scenario-trends/scenario-trends-settings/scenario-trends-settings.component.html
- src/app/scenario/scenario-trends/scenario-trends-settings/scenario-trends-settings.component.spec.ts
- src/app/scenario/scenario-trends/scenario-trends-settings/scenario-trends-settings.component.ts
- src/app/scenario/scenario-trends/scenario-trends.component.html
- src/app/scenario/scenario-trends/scenario-trends.component.scss
- src/app/scenario/scenario-trends/scenario-trends.component.ts
- src/app/scenario/scenario.component.ts
- src/app/scenario/scenario.module.ts
https://github.com/ludeknovy/jtl-reporter/issues/204
> scenario trends

- src/app/item-detail/item-detail.component.html
- src/app/item-detail/item-detail.component.ts
- src/app/items-api.service.ts
- src/app/items.service.model.ts
- src/app/scenario/add-new-item/add-new-item.component.html
- src/app/scenario/add-new-item/add-new-item.component.ts
- src/app/scenario/item-controls/item-controls.model.ts
- src/app/shared/shared-item/edit-item/edit-item.component.html
- src/app/shared/shared-item/edit-item/edit-item.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/209
> external link

- src/app/_services/chart-service-utils.ts
- src/app/item-detail/item-detail.component.html
- src/app/item-detail/item-detail.component.scss
- src/app/item-detail/item-detail.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/221
> thread groups

- src/app/item-detail/item-detail.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/221
> Fix: always setting the zoom range for overall chart

- src/app/scenario/scenario-trends/scenario-trends.component.ts
- src/app/scenario/scenario.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/234
> fix: scenario trends link

- src/app/_interceptors/mock-interceptor.ts
- src/app/_services/global-settings.model.ts
- src/app/_services/global-settings.service.ts
- src/app/administration/api-token/api-keys.module.ts
- src/app/administration/global-settings/global-settings.component.html
- src/app/administration/global-settings/global-settings.component.spec.ts
- src/app/administration/global-settings/global-settings.component.ts
- src/app/administration/global-settings/global-settings.module.ts
- src/app/administration/navigation/navigation.component.html
- src/app/administration/navigation/navigation.module.ts
- src/app/notification/notification-messages.ts
- src/app/notification/notification.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/237
> Feature: global settings

- .github/workflows/docker-hub-master.yml
- .github/workflows/docker-hub.yml
We are using jtl-reporter and planning on moving to arm-based nodes. Updating here so we don't have to build custom images.
> Add support for arm platforms

- src/app/item-detail/item-detail.component.html
- src/app/item-detail/item-detail.component.ts
- src/app/item-detail/request-stats/request-stats-compare.component.spec.ts
- src/app/items.service.model.ts
- src/app/scenario/add-new-item/add-new-item.model.ts
- src/app/scenario/item-controls/item-controls.model.ts
- src/app/scenario/scenario.component.html
- src/app/shared/shared-item/edit-item/edit-item.component.html
- src/app/shared/shared-item/edit-item/edit-item.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/262
> Edit item status

- src/app/top-panel/top-panel.component.html
https://github.com/ludeknovy/jtl-reporter/issues/264
> Remove API Docs link from top-panel

- src/app/scenario/external-notification/add-new-external-notification/add-new-external-notification.component.html
- src/app/scenario/external-notification/add-new-external-notification/add-new-external-notification.component.ts
- src/app/scenario/external-notification/external-notification.component.html
- src/app/scenario/external-notification/external-notification.component.ts
- src/app/scenario/external-notification/notificationConfig.ts
https://github.com/ludeknovy/jtl-reporter/issues/247
> Support for notification type - tables and forms extended

- src/app/item-detail/item-detail.component.html
- src/app/item-detail/request-stats/request-stats-compare.component.spec.ts
- src/app/items.service.model.ts
- src/app/shared/shared-project/project-settings/project-settings.component.html
- src/app/shared/shared-project/project-settings/project-settings.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/284
> Add 95% and 99% response time metrics to the report overview

- src/app/scenario/scenario-trends/scenario-trends.component.ts
https://github.com/ludeknovy/jtl-reporter/issues/289
> Fix: Refactor metric naming and mapping in scenario trends

- .github/workflows/build.yml
- .github/workflows/static-analysis.yml
- Dockerfile
Update base image to node20.8.0-alpine3.17
> Update node to v20

- src/app/item-detail/item-detail.component.html
- src/app/item-detail/monitoring-stats/monitoring-stats.component.css
- src/app/item-detail/monitoring-stats/monitoring-stats.component.html
- src/app/item-detail/monitoring-stats/monitoring-stats.component.ts
Replaced modal-based layout with a card-based layout in monitoring-stats.component.html to improve UI consistency. Added OnInit interface to MonitoringStatsComponent for better chart initialization. Removed redundant component placements and adjusted CSS styles for better spacing.
https://github.com/ludeknovy/jtl-reporter/issues/293
> Refactor monitoring stats layout and initialization
